language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
before_script:
  - gem install sass
  - sudo apt-get -y install nodejs nodejs-legacy npm
  - npm install -g yuglify
  - python manage.py collectstatic --noinput
script:
  - python manage.py test
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - chiedo@chie.do
    on_success: never
    on_failure: always
