# Don't use this for production purposes. Docker compose is only for development and staging servers
db:
  image: mysql
  env_file:
    - .env
  ports:
    - "5433:3306"
web:
  build: .
  command: python manage.py runserver 0.0.0.0:8000
  volumes:
    - .:/code
  ports:
    - "3001:8000"
  links:
    - db
  env_file:
    - .env
